version: "3"

volumes:
  db-data:
    external: false

services:
  db:
    image: "postgres:11.4"
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/db-data
    environment:
      POSTGRES_PASSWORD: "password"

  app:
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres:5432/dr_movil_development"
